const products=[{id:'bracelet-r001',name:'PULSEIRA RAGE R',price:429.90,image:'assets/products/rage-bracelet.png',copy:'Pulseira RAGE® prateada com elos R cravejados, acabamento polido e construção inspirada no monograma da marca.'}];
const $=id=>document.getElementById(id),money=n=>'€ '+Number(n).toFixed(2).replace('.',',');let current=products[0],size='18 CM';let cart=JSON.parse(localStorage.getItem('rageCart')||'[]');
function render(list=products){$('jewelryGrid').innerHTML=list.map((p,i)=>`<article class="card reveal" data-id="${p.id}" style="--delay:${i*80}ms"><div class="photo jewelPhoto"><span class="index">0${i+1}</span><img src="${p.image}" alt="${p.name}"><span class="quick">VER PRODUTO ↗</span></div><div class="cardMeta"><h3>${p.name}</h3><p>${money(p.price)}</p></div></article>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openProduct(c.dataset.id))}
function openProduct(id){current=products.find(p=>p.id===id)||products[0];$('mainImg').src=current.image;$('productName').textContent=current.name;$('price').textContent=money(current.price);$('productCopy').textContent=current.copy;$('modal').classList.add('open');document.body.classList.add('locked')}
function closeModal(){$('modal').classList.remove('open');document.body.classList.remove('locked')}
function cartRender(){$('cartCount').textContent=cart.length;$('cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cartRow"><span>${x.name}<small>${[x.color?String(x.color).toUpperCase():'',x.size||''].filter(Boolean).join(' · ')}</small></span><div class="cartActions"><b>${money(x.price)}</b><button class="removeItem" data-index="${i}" aria-label="Remover ${x.name}">REMOVER</button></div></div>`).join(''):'<p class="empty">Seu carrinho está vazio.</p>';$('total').textContent=money(cart.reduce((a,b)=>a+Number(b.price||0),0));localStorage.setItem('rageCart',JSON.stringify(cart));document.querySelectorAll('.removeItem').forEach(btn=>btn.onclick=()=>{cart.splice(Number(btn.dataset.index),1);cartRender()})}
$('close').onclick=closeModal;document.querySelectorAll('.jewelSizes button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.jewelSizes button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');size=b.textContent});$('add').onclick=()=>{cart.push({id:current.id,name:current.name,price:current.price,size,type:'jewelry'});cartRender();$('drawer').classList.add('open')};$('cartBtn').onclick=()=>$('drawer').classList.add('open');$('drawerClose').onclick=()=>$('drawer').classList.remove('open');$('jewelSort').onchange=()=>{let a=[...products];if($('jewelSort').value==='low')a.sort((x,y)=>x.price-y.price);if($('jewelSort').value==='high')a.sort((x,y)=>y.price-x.price);render(a)};render();cartRender();

const photoTab=document.getElementById('photoTab'),modelTab=document.getElementById('modelTab'),modelWrap=document.getElementById('modelWrap'),mainImg=document.getElementById('mainImg');
function setJewelView(mode){const is3d=mode==='3d';mainImg.hidden=is3d;modelWrap.hidden=!is3d;photoTab.classList.toggle('selected',!is3d);modelTab.classList.toggle('selected',is3d)}
photoTab.addEventListener('click',()=>setJewelView('photo'));modelTab.addEventListener('click',()=>setJewelView('3d'));

(async()=>{try{const r=await fetch('/api/products');if(!r.ok)return;const d=await r.json();const db=d.products.find(p=>p.id==='bracelet-r001');if(db){products[0].name=db.name;products[0].price=Number(db.price);current=products[0];render()}}catch{}})();
