const products = [
    { id: 'tee-black', name: 'RAGE T-SHIRT — BLACK', price: 189.90, order: 1, defaultColor: 'black', colors: { black: { front: 'assets/products/rage-black-tee.png', back: 'assets/products/rage-black-tee-back.png' }, white: { front: 'assets/products/rage-white-tee-front.png', back: 'assets/products/rage-white-tee.png' } } },
    { id: 'tee-white', name: 'RAGE T-SHIRT — WHITE', price: 189.90, order: 2, defaultColor: 'white', colors: { black: { front: 'assets/products/rage-black-tee.png', back: 'assets/products/rage-black-tee-back.png' }, white: { front: 'assets/products/rage-white-tee-front.png', back: 'assets/products/rage-white-tee.png' } } }
];
let current = null, color = 'black', view = 'front', size = 'M'; const $ = id => document.getElementById(id), money = n => '€ ' + n.toFixed(2).replace('.', ',');
function render(list = products) { $('grid').innerHTML = list.map((p, i) => `<article class="card reveal" data-id="${p.id}" style="--delay:${i * 80}ms"><div class="photo"><span class="index">0${i + 1}</span><img src="${p.colors[p.defaultColor].front}" alt="${p.name}"><span class="quick">VER PRODUTO ↗</span></div><div class="cardMeta"><h3>${p.name}</h3><p>${money(p.price)}</p></div></article>`).join(''); document.querySelectorAll('.card').forEach(c => c.onclick = () => openProduct(c.dataset.id)) }
function openProduct(id) { current = products.find(p => p.id === id); color = current.defaultColor; view = 'front'; $('productName').textContent = current.name; $('price').textContent = money(current.price); update(); $('modal').classList.add('open'); document.body.classList.add('locked') }
function update() { $('mainImg').src = current.colors[color][view]; $('viewLabel').textContent = view === 'front' ? 'FRENTE' : 'COSTAS'; $('frontBtn').classList.toggle('active', view === 'front'); $('backBtn').classList.toggle('active', view === 'back'); document.querySelectorAll('.swatches button').forEach(b => b.classList.toggle('selected', b.dataset.color === color)) }
$('frontBtn').onclick = () => { view = 'front'; update() }; $('backBtn').onclick = () => { view = 'back'; update() }; document.querySelectorAll('.swatches button').forEach(b => b.onclick = () => { color = b.dataset.color; update() }); document.querySelectorAll('.sizes button').forEach(b => b.onclick = () => { document.querySelectorAll('.sizes button').forEach(x => x.classList.remove('selected')); b.classList.add('selected'); size = b.textContent }); $('close').onclick = closeModal; function closeModal() { $('modal').classList.remove('open'); document.body.classList.remove('locked') }
let cart = JSON.parse(localStorage.rageCart || '[]'); function cartRender() { $('cartCount').textContent = cart.length; $('cartItems').innerHTML = cart.length ? cart.map((x, i) => `<div class="cartRow"><span>${x.name}<small>${[x.color ? String(x.color).toUpperCase() : '', x.size || ''].filter(Boolean).join(' · ')}</small></span><div class="cartActions"><b>${money(x.price)}</b><button class="removeItem" data-index="${i}" aria-label="Remover ${x.name}">REMOVER</button></div></div>`).join('') : '<p class="empty">Seu carrinho está vazio.</p>'; $('total').textContent = money(cart.reduce((a, b) => a + b.price, 0)); localStorage.rageCart = JSON.stringify(cart); document.querySelectorAll('.removeItem').forEach(btn => btn.onclick = () => { cart.splice(Number(btn.dataset.index), 1); cartRender(); }); } $('add').onclick = () => { cart.push({ id: current.id, name: current.name, price: current.price, color, size }); cartRender(); $('drawer').classList.add('open') }; $('cartBtn').onclick = () => $('drawer').classList.add('open'); $('drawerClose').onclick = () => $('drawer').classList.remove('open'); $('sort').onchange = () => { let a = [...products]; if ($('sort').value === 'new') a.sort((x, y) => y.order - x.order); if ($('sort').value === 'az') a.sort((x, y) => x.name.localeCompare(y.name)); render(a) }; render(); cartRender();
