'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const mysql=require('mysql2/promise');
const ROOT=__dirname, envFile=path.join(ROOT,'.env');
if(fs.existsSync(envFile)){for(const line of fs.readFileSync(envFile,'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);if(!m||m[1] in process.env)continue;let v=m[2];if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);process.env[m[1]]=v}}
const PORT=Number(process.env.PORT||3000),isProd=process.env.NODE_ENV==='production',MAX_BODY=65536,SESSION_MS=2592000000;
const DB={host:process.env.DB_HOST||'localhost',port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||'root',password:process.env.DB_PASSWORD||'',database:process.env.DB_NAME||'rage',waitForConnections:true,connectionLimit:Number(process.env.DB_POOL_MAX||10),queueLimit:0,charset:'utf8mb4'};
const pool=mysql.createPool(DB);
const CATALOG={'tee-black':{name:'RAGE T-SHIRT — BLACK',priceCents:18990,type:'clothing'},'tee-white':{name:'RAGE T-SHIRT — WHITE',priceCents:18990,type:'clothing'},'bracelet-r001':{name:'PULSEIRA RAGE R',priceCents:42990,type:'jewelry'}};
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.glb':'model/gltf-binary','.gltf':'model/gltf+json','.ico':'image/x-icon'};
async function initDb(){
 await pool.query(`CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(80) NOT NULL,email VARCHAR(254) NOT NULL UNIQUE,password_hash TEXT NOT NULL,role ENUM('customer','admin') NOT NULL DEFAULT 'customer',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
 try{await pool.query("ALTER TABLE users ADD COLUMN role ENUM('customer','admin') NOT NULL DEFAULT 'customer' AFTER password_hash")}catch(e){if(e.code!=='ER_DUP_FIELDNAME')throw e}
 const adminEmail=normalizeEmail(process.env.ADMIN_EMAIL||'');if(adminEmail)await pool.execute("UPDATE users SET role='admin' WHERE email=?",[adminEmail]);
 await pool.query(`CREATE TABLE IF NOT EXISTS sessions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,expires_at BIGINT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_sessions_expiry(expires_at),CONSTRAINT fk_sessions_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
 await pool.query(`CREATE TABLE IF NOT EXISTS products (id VARCHAR(80) PRIMARY KEY,name VARCHAR(255) NOT NULL,price_cents INT UNSIGNED NOT NULL,type VARCHAR(40) NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
 await pool.query(`CREATE TABLE IF NOT EXISTS orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,customer_name VARCHAR(120) NOT NULL,address VARCHAR(200) NOT NULL,city VARCHAR(100) NOT NULL,postal_code VARCHAR(30) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'CONFIRMADO',total_cents INT UNSIGNED NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_orders_user(user_id,created_at),CONSTRAINT fk_orders_user FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
 await pool.query(`CREATE TABLE IF NOT EXISTS order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,product_id VARCHAR(80) NOT NULL,name VARCHAR(255) NOT NULL,price_cents INT UNSIGNED NOT NULL,quantity INT UNSIGNED NOT NULL,variant JSON NOT NULL,CONSTRAINT fk_items_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
 for(const[id,p]of Object.entries(CATALOG))await pool.execute(`INSERT INTO products(id,name,price_cents,type,active) VALUES(?,?,?,?,TRUE) ON DUPLICATE KEY UPDATE name=VALUES(name),price_cents=VALUES(price_cents),type=VALUES(type),active=TRUE`,[id,p.name,p.priceCents,p.type]);
}
function json(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(data))}
function parseCookies(req){const out={};for(const part of(req.headers.cookie||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
const tokenHash=t=>crypto.createHash('sha256').update(t).digest('hex');
const cookie=(token,maxAge=Math.floor(SESSION_MS/1000))=>`rage_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${isProd?'; Secure':''}`;
const normalizeEmail=v=>String(v||'').trim().toLowerCase(),validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)&&v.length<=254;
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return`scrypt$${salt}$${crypto.scryptSync(password,salt,64).toString('hex')}`}
function verifyPassword(password,stored){try{const[algo,salt,hash]=stored.split('$');if(algo!=='scrypt')return false;const a=crypto.scryptSync(password,salt,64),e=Buffer.from(hash,'hex');return a.length===e.length&&crypto.timingSafeEqual(a,e)}catch{return false}}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(Buffer.byteLength(raw)>MAX_BODY){reject(new Error('too_large'));req.destroy()}});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('invalid_json'))}});req.on('error',reject)})}
async function currentUser(req){const t=parseCookies(req).rage_session;if(!t)return null;const[rows]=await pool.execute(`SELECT u.id,u.name,u.email,u.role,u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? LIMIT 1`,[tokenHash(t),Date.now()]);return rows[0]||null}
async function newSession(uid){const t=crypto.randomBytes(32).toString('base64url');await pool.execute('INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(?,?,?)',[uid,tokenHash(t),Date.now()+SESSION_MS]);return t}
async function cleanup(){try{await pool.execute('DELETE FROM sessions WHERE expires_at<=?',[Date.now()])}catch(e){console.error('Falha ao limpar sessões:',e.message)}}
async function adminUser(req){const u=await currentUser(req);return u&&u.role==='admin'?u:null}
function adminDenied(res,u){return json(res,u?403:401,{error:u?'Acesso reservado ao administrador.':'Faça login.'})}
async function api(req,res,url){try{
 if(req.method==='GET'&&url.pathname==='/api/health'){await pool.query('SELECT 1');return json(res,200,{ok:true,database:'mysql'})}
 if(req.method==='GET'&&url.pathname==='/api/products'){const[rows]=await pool.query('SELECT id,name,price_cents,type FROM products WHERE active=TRUE ORDER BY id');return json(res,200,{products:rows.map(p=>({...p,price:Number(p.price_cents)/100}))})}
 if(req.method==='POST'&&url.pathname==='/api/register'){let b;try{b=await body(req)}catch{return json(res,400,{error:'Requisição inválida.'})}const name=String(b.name||'').trim().replace(/\s+/g,' '),email=normalizeEmail(b.email),password=String(b.password||'');if(name.length<2||name.length>80)return json(res,400,{error:'Informe um nome válido.'});if(!validEmail(email))return json(res,400,{error:'Informe um e-mail válido.'});if(password.length<8||password.length>128)return json(res,400,{error:'A senha deve ter entre 8 e 128 caracteres.'});try{const[r]=await pool.execute('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)',[name,email,hashPassword(password)]);const id=Number(r.insertId),token=await newSession(id);return json(res,201,{ok:true,user:{id,name,email,role:'customer'}},{'Set-Cookie':cookie(token)})}catch(e){if(e.code==='ER_DUP_ENTRY')return json(res,409,{error:'Já existe uma conta com este e-mail.'});throw e}}
 if(req.method==='POST'&&url.pathname==='/api/login'){let b;try{b=await body(req)}catch{return json(res,400,{error:'Requisição inválida.'})}const email=normalizeEmail(b.email),password=String(b.password||'');const[rows]=await pool.execute('SELECT id,name,email,password_hash,role FROM users WHERE email=? LIMIT 1',[email]);const u=rows[0];if(!u||!verifyPassword(password,u.password_hash))return json(res,401,{error:'E-mail ou senha incorretos.'});const token=await newSession(u.id);return json(res,200,{ok:true,user:{id:Number(u.id),name:u.name,email:u.email,role:u.role}},{'Set-Cookie':cookie(token)})}
 if(req.method==='POST'&&url.pathname==='/api/logout'){const t=parseCookies(req).rage_session;if(t)await pool.execute('DELETE FROM sessions WHERE token_hash=?',[tokenHash(t)]);return json(res,200,{ok:true},{'Set-Cookie':cookie('',0)})}
 if(req.method==='GET'&&url.pathname==='/api/me'){const u=await currentUser(req);return u?json(res,200,{user:{...u,id:Number(u.id)}}):json(res,401,{user:null})}
 if(req.method==='GET'&&url.pathname==='/api/orders'){const u=await currentUser(req);if(!u)return json(res,401,{error:'Faça login para ver seus pedidos.'});const[orders]=await pool.execute('SELECT id,status,total_cents,created_at FROM orders WHERE user_id=? ORDER BY created_at DESC',[u.id]);for(const o of orders){const[items]=await pool.execute('SELECT name,quantity,price_cents,variant FROM order_items WHERE order_id=? ORDER BY id',[o.id]);o.items=items.map(i=>({...i,variant:typeof i.variant==='string'?JSON.parse(i.variant):i.variant}));o.id=Number(o.id);o.total=Number(o.total_cents)/100}return json(res,200,{orders})}
 if(req.method==='POST'&&url.pathname==='/api/orders'){const u=await currentUser(req);if(!u)return json(res,401,{error:'Faça login antes de finalizar a compra.'});let b;try{b=await body(req)}catch{return json(res,400,{error:'Dados do pedido inválidos.'})}const customerName=String(b.customerName||'').trim(),address=String(b.address||'').trim(),city=String(b.city||'').trim(),postalCode=String(b.postalCode||'').trim();if(customerName.length<2||address.length<5||city.length<2||postalCode.length<4)return json(res,400,{error:'Preencha corretamente os dados de entrega.'});if(!Array.isArray(b.items)||b.items.length<1||b.items.length>50)return json(res,400,{error:'O carrinho está vazio ou inválido.'});const normalized=[];let total=0;for(const raw of b.items){const productId=String(raw.productId||raw.id||'');const[pr]=await pool.execute('SELECT id,name,price_cents,type FROM products WHERE id=? AND active=TRUE LIMIT 1',[productId]);const row=pr[0];if(!row)return json(res,400,{error:'Existe um produto inválido ou inativo no carrinho.'});const p={name:row.name,priceCents:Number(row.price_cents),type:row.type};const quantity=Math.max(1,Math.min(10,parseInt(raw.quantity||1,10)||1)),variant={};if(raw.color)variant.color=String(raw.color).slice(0,30);if(raw.size)variant.size=String(raw.size).slice(0,30);normalized.push({productId,p,quantity,variant});total+=p.priceCents*quantity}const c=await pool.getConnection();try{await c.beginTransaction();const[r]=await c.execute('INSERT INTO orders(user_id,customer_name,address,city,postal_code,total_cents) VALUES(?,?,?,?,?,?)',[u.id,customerName,address,city,postalCode,total]);for(const x of normalized)await c.execute('INSERT INTO order_items(order_id,product_id,name,price_cents,quantity,variant) VALUES(?,?,?,?,?,?)',[r.insertId,x.productId,x.p.name,x.p.priceCents,x.quantity,JSON.stringify(x.variant)]);await c.commit();return json(res,201,{ok:true,order:{id:Number(r.insertId),total:total/100}})}catch(e){await c.rollback();throw e}finally{c.release()}}

 if(url.pathname.startsWith('/api/admin/')){
   const signed=await currentUser(req);const admin=signed&&signed.role==='admin'?signed:null;if(!admin)return adminDenied(res,signed);
   if(req.method==='GET'&&url.pathname==='/api/admin/overview'){
     const[[uc],[pc],[oc],[rv], [users], [products], [orders]]=await Promise.all([
       pool.query('SELECT COUNT(*) n FROM users'),pool.query('SELECT COUNT(*) n FROM products WHERE active=TRUE'),pool.query('SELECT COUNT(*) n FROM orders'),pool.query('SELECT COALESCE(SUM(total_cents),0) n FROM orders WHERE status<>\'CANCELADO\''),
       pool.query('SELECT id,name,email,role,created_at FROM users ORDER BY created_at DESC LIMIT 200'),pool.query('SELECT id,name,price_cents,type,active,updated_at FROM products ORDER BY id'),pool.query('SELECT o.id,o.customer_name,o.status,o.total_cents,o.created_at,u.email FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC LIMIT 200')]);
     return json(res,200,{admin:{id:Number(admin.id),name:admin.name,email:admin.email},stats:{users:Number(uc[0].n),products:Number(pc[0].n),orders:Number(oc[0].n),revenue:Number(rv[0].n)/100},users:users.map(x=>({...x,id:Number(x.id)})),products:products.map(x=>({...x,price_cents:Number(x.price_cents),active:Boolean(x.active)})),orders:orders.map(x=>({...x,id:Number(x.id),total_cents:Number(x.total_cents)}))});
   }
   if(req.method==='POST'&&url.pathname==='/api/admin/products/restore'){
     for(const[id,p]of Object.entries(CATALOG))await pool.execute(`INSERT INTO products(id,name,price_cents,type,active) VALUES(?,?,?,?,TRUE) ON DUPLICATE KEY UPDATE name=VALUES(name),price_cents=VALUES(price_cents),type=VALUES(type),active=TRUE`,[id,p.name,p.priceCents,p.type]);
     return json(res,200,{ok:true,message:'Catálogo restaurado.'});
   }
   let m=url.pathname.match(/^\/api\/admin\/products\/([^/]+)$/);if(req.method==='PATCH'&&m){let b;try{b=await body(req)}catch{return json(res,400,{error:'Dados inválidos.'})}const name=String(b.name||'').trim(),type=String(b.type||'').trim(),price=Math.round(Number(b.price)*100),active=b.active?1:0;if(name.length<2||type.length<2||!Number.isFinite(price)||price<0)return json(res,400,{error:'Produto inválido.'});const[r]=await pool.execute('UPDATE products SET name=?,price_cents=?,type=?,active=? WHERE id=?',[name,price,type,active,decodeURIComponent(m[1])]);if(!r.affectedRows)return json(res,404,{error:'Produto não encontrado.'});return json(res,200,{ok:true})}
   m=url.pathname.match(/^\/api\/admin\/orders\/(\d+)$/);if(req.method==='PATCH'&&m){let b;try{b=await body(req)}catch{return json(res,400,{error:'Dados inválidos.'})}const status=String(b.status||'').toUpperCase(),allowed=['CONFIRMADO','EM PREPARAÇÃO','ENVIADO','ENTREGUE','CANCELADO'];if(!allowed.includes(status))return json(res,400,{error:'Status inválido.'});const[r]=await pool.execute('UPDATE orders SET status=? WHERE id=?',[status,Number(m[1])]);if(!r.affectedRows)return json(res,404,{error:'Pedido não encontrado.'});return json(res,200,{ok:true})}
 }
 return json(res,404,{error:'Rota não encontrada.'})
 }catch(e){console.error('Erro da API:',e);return json(res,500,{error:'Erro interno do servidor.'})}}
function serve(req,res,url){let pathname;try{pathname=decodeURIComponent(url.pathname)}catch{res.writeHead(400);return res.end('Bad Request')}if(pathname==='/')pathname='/index.html';const safe=path.normalize(pathname).replace(/^(\.\.(\/|\\|$))+/,''),file=path.join(ROOT,safe);if(!file.startsWith(ROOT)||path.basename(file)==='.env'){res.writeHead(403);return res.end('Forbidden')}fs.stat(file,(err,st)=>{if(err||!st.isFile()){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('404')}const ext=path.extname(file).toLowerCase();res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; img-src 'self' data:; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' https://unpkg.com; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"});fs.createReadStream(file).pipe(res)})}
(async()=>{try{await initDb();await cleanup();setInterval(cleanup,3600000).unref();http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);return url.pathname.startsWith('/api/')?api(req,res,url):serve(req,res,url)}).listen(PORT,()=>console.log(`RAGE® + MySQL rodando em http://localhost:${PORT}`))}catch(e){console.error('\nNão foi possível conectar/inicializar o MySQL.');console.error('Detalhe:',e.message);console.error('\nConfira: 1) MySQL está ligado; 2) banco rage existe; 3) DB_USER/DB_PASSWORD do .env; 4) porta 3306.\n');process.exit(1)}})();
